# generated by datamodel-codegen:
#   filename:  advisory.yaml
#   timestamp: 2025-07-22T19:10:28+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel


class AdvisoryRequest(BaseModel):
    question: Optional[str] = None


class Source(BaseModel):
    uri: Optional[str] = None
    title: Optional[str] = None


class Support(BaseModel):
    text: Optional[str] = None
    chunks: Optional[List[int]] = None


class Grounding(BaseModel):
    queries: Optional[List[str]] = None
    sources: Optional[List[Source]] = None
    supports: Optional[List[Support]] = None
    search_html: Optional[str] = None


class AdvisoryResponse(BaseModel):
    question: Optional[str] = None
    timestamp: Optional[datetime] = None
    answer_text: Optional[str] = None
    grounding: Optional[Grounding] = None
