# generated by datamodel-codegen:
#   filename:  alerts.yaml
#   timestamp: 2025-07-24T14:07:02+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class ReminderInput(BaseModel):
    message: str
    when: datetime


class ReminderStatus(BaseModel):
    status: str = Field(..., example='success')
    reminder_id: str


class Reminder(BaseModel):
    reminder_id: str
    message: str
    when: datetime
    audio_url: Optional[str] = None
