# generated by datamodel-codegen:
#   filename:  audio.yaml
#   timestamp: 2025-07-20T14:34:30+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class AudioRequest(BaseModel):
    text: str = Field(
        ...,
        description='The text to be converted into audio',
        example='Hello, how are you?',
    )
    language: str = Field(
        ...,
        description='Language code for the speech output (e.g., "en-US", "fr-FR")',
        example='en-US',
    )


class AudioResponse(BaseModel):
    audio_url: Optional[str] = Field(
        None,
        description='URL to the generated MP3 file (valid for under 5 minutes)',
        example='https://firebase.storage.googleapis.com/path/to/audio.mp3',
    )
class ErrorResponse(BaseModel):
    detail: str = Field(
        ...,
        description='Description of the error that occurred',
        example='Failed to generate audio due to an internal error.'
    )