# generated by datamodel-codegen:
#   filename:  community-connector.yaml
#   timestamp: 2025-07-24T14:07:02+00:00

from __future__ import annotations

from pydantic import BaseModel


class FAQItem(BaseModel):
    question: str
    answer: str


class CommunityConnectRequest(BaseModel):
    location: str
    interest: str


class CommunityConnectResponse(BaseModel):
    group_name: str
    whatsapp_link: str
