# generated by datamodel-codegen:
#   filename:  crop-diagnosis.yaml
#   timestamp: 2025-07-24T14:07:02+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class CropDiagnosis(BaseModel):
    diagnosis: Optional[str] = None
    confidence: Optional[float] = None
    recommended_actions: Optional[List[str]] = None
    audio_url: Optional[str] = None
