# generated by datamodel-codegen:
#   filename:  financial-planner.yaml
#   timestamp: 2025-07-24T14:07:02+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class FinancialPlan(BaseModel):
    total_cost: Optional[float] = None
    expected_income: Optional[float] = None
    net_profit: Optional[float] = None
    break_even_price: Optional[float] = None
