# generated by datamodel-codegen:
#   filename:  inventory-vendor.yaml
#   timestamp: 2025-07-24T14:07:02+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel


class StockItem(BaseModel):
    item_name: Optional[str] = None
    quantity: Optional[float] = None


class StockLog(BaseModel):
    item_name: Optional[str] = None
    used: Optional[float] = None
    timestamp: Optional[datetime] = None


class ReorderSuggestion(BaseModel):
    item_name: Optional[str] = None
    need_quantity: Optional[float] = None
    vendor_id: Optional[str] = None
    price_per_unit: Optional[float] = None
    audio_url: Optional[str] = None


class Order(BaseModel):
    order_id: str
    farmer_id: str
    item_name: str
    quantity: float
    timestamp: datetime
