# generated by datamodel-codegen:
#   filename:  market-analysis.yaml
#   timestamp: 2025-07-24T14:07:02+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class MarketPrice(BaseModel):
    crop: Optional[str] = None
    mandi: Optional[str] = None
    price: Optional[float] = None
    trend: Optional[str] = None
    advice: Optional[str] = None
    audio_url: Optional[str] = None
