# generated by datamodel-codegen:
#   filename:  orchestrator.yaml
#   timestamp: 2025-07-24T14:07:02+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class NextAction(BaseModel):
    agent: Optional[str] = None
    payload: Optional[Dict[str, Any]] = None


class AgentResponse(BaseModel):
    reply_text: Optional[str] = None
    reply_audio_url: Optional[str] = None
    follow_up_intent: Optional[str] = None
    next_actions: Optional[List[NextAction]] = None
