# generated by datamodel-codegen:
#   filename:  scheme-navigator.yaml
#   timestamp: 2025-07-24T14:07:02+00:00

from __future__ import annotations

from datetime import datetime   
from typing import Optional

from pydantic import BaseModel, ConfigDict


class Scheme(BaseModel):
    scheme_id: Optional[str] = None
    scheme_name: Optional[str] = None
    description: Optional[str] = None
    deadline: Optional[datetime] = None
    model_config = ConfigDict(from_attributes=True)


class ApplicationStatus(BaseModel):
    status: Optional[str] = None
    reference_id: Optional[str] = None
    audio_url: Optional[str] = None
