# generated by datamodel-codegen:
#   filename:  sos-agent.yaml
#   timestamp: 2025-07-24T14:07:02+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class SosRequest(BaseModel):
    farmer_id: str
    emergency_type: str


class Status(Enum):
    dispatched = 'dispatched'
    pending = 'pending'
    failed = 'failed'


class SosResponse(BaseModel):
    status: Status = Field(..., example='dispatched')
    reference_id: str
