# generated by datamodel-codegen:
#   filename:  translate.yaml
#   timestamp: 2025-07-20T11:39:21+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

# Request body model
# class TranslationRequest(BaseModel):
#     text: str
#     target_language: str  # e.g., French, Hindi, Spanish


class TranslationRequest(BaseModel):
    text: Optional[str] = None
    target_language: Optional[str] = None


class TranslationResponse(BaseModel):
    translated_phrase: Optional[str] = None
