# generated by datamodel-codegen:
#   filename:  transcribe.yaml
#   timestamp: 2025-07-20T19:50:46+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class TranscribeRequest(BaseModel):
    file: Optional[bytes] = Field(
        None,
        description='Audio file to transcribe. Can be in any common format (e.g., MP3, WAV, M4A). Will be converted to LINEAR16 at 16kHz automatically.\n',
    )


class TranscribeResponse(BaseModel):
    transcript: Optional[str] = Field(
        None, description='The transcribed text of the input audio'
    )


class ErrorResponse(BaseModel):
    error: Optional[str] = Field(None, description='Description of the error')
