# generated by datamodel-codegen:
#   filename:  translate.yaml
#   timestamp: 2025-07-20T11:39:21+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class TranslationRequest(BaseModel):
    phrase: Optional[str] = None
    target_language: Optional[str] = None


class TranslationResponse(BaseModel):
    translated_phrase: Optional[str] = None
