# generated by datamodel-codegen:
#   filename:  weather-advisory.yaml
#   timestamp: 2025-07-24T14:07:02+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class WeatherAdvisory(BaseModel):
    forecast: Optional[str] = None
    critical_alerts: Optional[List[str]] = None
    recommendations: Optional[List[str]] = None
    audio_url: Optional[str] = None
